### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')

### ISSUE THREAD

**Issue by quytxv** [jazz-soft/react-midi-player#2]
After I added `MidiPayer` into a page or a modal, if I change page or close modal, this error happens.
Could you fix it please? @jazz-soft 

```
react-midi-player.js:96 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at react-midi-player.js:96:1
    at safelyCallDestroy (react-dom.development.js:22932:1)
    at commitHookEffectListUnmount (react-dom.development.js:23100:1)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:25098:1)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:25048:1)
    at commitPassiveUnmountEffects_begin (react-dom.development.js:24956:1)
    at commitPassiveUnmountEffects (react-dom.development.js:24941:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27038:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at commitRootImpl (react-dom.development.js:26935:1)
    at commitRoot (react-dom.development.js:26682:1)
    at performSyncWorkOnRoot (react-dom.development.js:26117:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at react-dom.development.js:25651:1
```
<img width="962" alt="Screen Shot 2022-10-04 at 17 17 54" src="https://user-images.githubusercontent.com/48816787/193795638-a1740dc9-aaae-4918-bf66-99f3b409f909.png">

**Comment by jazz-soft** [comment]
What is `ref.current` set to?

**Comment by quytxv** [comment]
@jazz-soft 
Thank you for your response.
When I close modal, ref.current is `null`.
This is sandbox to reproduce.
https://codesandbox.io/s/silent-smoke-c3i6h1?file=/src/App.js

**Comment by jazz-soft** [comment]
Thanks for the sandbox!
Please try to update to the latest release.
